import { prisma } from "@pkos/database";
import { Activity, AlertTriangle, GitMerge, Settings, ShieldAlert, CheckCircle2 } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function HealthDashboardPage() {
  // Actionable metrics
  const unreviewedObservations = await prisma.observation.count({ where: { state: "HYPOTHESIS" } });
  const brokenResources = await prisma.resource.count({ where: { status: "ERROR" } });
  
  // Stale items (simulated for now since aging isn't fully wired)
  const staleSummaries = 0;
  const staleRelationships = await prisma.relationship.count({ where: { confidence: { lt: 0.5 } } });
  
  return (
    <div className="p-8 pt-24 max-w-4xl mx-auto min-h-screen bg-[#0A0A0A] text-slate-200">
      
      <div className="mb-12">
        <h1 className="text-3xl font-light text-white tracking-tight flex items-center gap-4">
          <Activity className="w-8 h-8 text-emerald-400" />
          Knowledge Health
        </h1>
        <p className="text-slate-400 mt-2">Actionable maintenance queue for your personal knowledge system.</p>
      </div>

      <div className="space-y-4">
        
        {/* Item 1 */}
        <div className="group flex items-start gap-4 p-5 rounded-2xl border border-rose-500/20 bg-rose-500/5 hover:bg-rose-500/10 transition-colors cursor-pointer">
          <div className="p-3 bg-rose-500/10 text-rose-500 rounded-xl shrink-0">
            <AlertTriangle className="w-6 h-6" />
          </div>
          <div className="flex-1">
            <div className="flex justify-between items-start">
              <h3 className="text-lg font-medium text-white group-hover:text-rose-400 transition-colors">Broken Resources</h3>
              <span className="px-3 py-1 bg-rose-500/20 text-rose-400 rounded-full text-sm font-semibold">{brokenResources}</span>
            </div>
            <p className="text-slate-400 text-sm mt-1">Resources that failed to synchronize with external providers.</p>
            <div className="mt-4">
              <button className="text-sm font-medium text-rose-400 hover:text-rose-300">Review & Fix →</button>
            </div>
          </div>
        </div>

        {/* Item 2 */}
        <div className="group flex items-start gap-4 p-5 rounded-2xl border border-amber-500/20 bg-amber-500/5 hover:bg-amber-500/10 transition-colors cursor-pointer">
          <div className="p-3 bg-amber-500/10 text-amber-500 rounded-xl shrink-0">
            <GitMerge className="w-6 h-6" />
          </div>
          <div className="flex-1">
            <div className="flex justify-between items-start">
              <h3 className="text-lg font-medium text-white group-hover:text-amber-400 transition-colors">Unreviewed Observations</h3>
              <span className="px-3 py-1 bg-amber-500/20 text-amber-400 rounded-full text-sm font-semibold">{unreviewedObservations}</span>
            </div>
            <p className="text-slate-400 text-sm mt-1">Hypotheses generated by PKOS that need your verification to become facts.</p>
            <div className="mt-4">
              <button className="text-sm font-medium text-amber-400 hover:text-amber-300">Verify Hypotheses →</button>
            </div>
          </div>
        </div>

        {/* Item 3 */}
        <div className="group flex items-start gap-4 p-5 rounded-2xl border border-slate-700/50 bg-slate-800/30 hover:bg-slate-800/50 transition-colors cursor-pointer">
          <div className="p-3 bg-slate-700/50 text-slate-400 rounded-xl shrink-0">
            <ShieldAlert className="w-6 h-6" />
          </div>
          <div className="flex-1">
            <div className="flex justify-between items-start">
              <h3 className="text-lg font-medium text-white group-hover:text-indigo-400 transition-colors">Low Confidence Relationships</h3>
              <span className="px-3 py-1 bg-slate-700 text-slate-300 rounded-full text-sm font-semibold">{staleRelationships}</span>
            </div>
            <p className="text-slate-400 text-sm mt-1">Relationships generated by the AI that have very low confidence.</p>
            <div className="mt-4">
              <button className="text-sm font-medium text-indigo-400 hover:text-indigo-300">Prune Relationships →</button>
            </div>
          </div>
        </div>

        {/* All Clear */}
        {brokenResources === 0 && unreviewedObservations === 0 && staleRelationships === 0 && (
          <div className="flex flex-col items-center justify-center p-12 rounded-2xl border border-emerald-500/20 bg-emerald-500/5">
            <CheckCircle2 className="w-16 h-16 text-emerald-500 mb-4" />
            <h3 className="text-xl font-medium text-emerald-400">System Healthy</h3>
            <p className="text-emerald-500/70 mt-2 text-center max-w-md">Your knowledge graph is clean and fully synchronized. No maintenance required.</p>
          </div>
        )}

      </div>
    </div>
  );
}
